name: test_flutter_supabase_food_delivery_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  readmore: ^3.0.0
  supabase_flutter: ^2.8.4
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  iconsax: ^0.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
